version: "3.7"
services:
  app:
    build:
      args:
        user: fcms
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: fcms
    container_name: fcms-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - fcms

  db:
    image: mariadb
    container_name: fcms-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - fcms

  nginx:
    image: nginx:alpine
    container_name: fcms-nginx
    restart: unless-stopped
    ports:
      - 8003:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - fcms
      
networks:
  fcms:
    driver: bridge
