version: "3.7"
services:
  app:
    image: fcms
    container_name: fcms-app
    restart: unless-stopped
    networks:
      - fcms-network

  db:
    image: mariadb
    container_name: fcms-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - fcms-network

  nginx:
    image: nginx:alpine
    container_name: fcms-nginx
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ../:/var/www
      - ../docker/nginx:/etc/nginx/conf.d
    networks:
      - fcms-network

networks:
  fcms-network:
    driver: bridge
